version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
      - image: redis
    working_directory: /go/src/github.com/chapsuk/worker
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
